#!/bin/bash
################################################################################
# Script for automatic generation of correction file with the right values
# inserted in place of predefined markers in the file.
#
# The script outputs to stdout for clients to decide to redirect output to the
# file of their choice
################################################################################

################################################################################
# Option parsing with error checking
################################################################################
tp=-1
team=-1
correcter=Nemo
section=-1
while [[ $# -gt 0 ]]
do
    option="$1"
	optarg="$2"
    case $option in
        --tp)
			tp="$optarg"
			shift
			;;
        --team)
			team="$optarg"
			shift
			;;
        --correcter)
			correcter="$optarg"
			shift
			;;
        --section)
			section="$optarg"
			shift
			;;
        *)
            echo "$0 : ERROR : unknown option: $option" >& 2
            exit 1
			;;
    esac
shift
done

if [[ $tp == -1 ]] ; then
	echo "$0 : ERROR : Tp number must be specified" >& 2
	exit 1
fi
if [[ $team == -1 ]] ; then
	echo "$0 : ERROR : Team number must be specified" >& 2
	exit 1
fi
if [[ "$correcter" == Nemo ]] ; then
	echo "$0 : ERROR : Correcter name must be specified" >& 2
	exit 1
fi
if [[ $section == -1 ]] ; then
	echo "$0 : ERROR : section number must be specified" >& 2
	exit 1
fi

################################################################################
# Use sed to replace pre-defined markers with the values given to the script and
# output to stdout
################################################################################
sed "s/__TEAM_NUMBER__/$team/" correction.txt |
	sed "s/__SECTION__/$section/" |
	sed "s/__TRAVAIL_PRATIQUE__/$tp/" |
	sed "s/__CORRECTEUR__/$correcter/"
