#!/bin/bash
################################################################################
# This script looks up for a given team size (2 or 4) and a given section, the
# team numbers for that section.
#
# Based on the team size and section number, it downloads the right .php file
# from the course website.
#
# Then though a couple of grep and sed commands, extracts the team numbers which
# it outputs to stdout for other scripts to use.
################################################################################


################################################################################
################################################################################
section=2
team_size=4
while [[ $# -gt 0 ]]
do
    option="$1"
	optarg="$2"
    case $option in
        -t|--team-size)
			team_size="$optarg"
			shift
			;;
        -s|--section)
			section="$optarg"
			shift
			;;
        *)
            echo "$0 : ERROR : unknown option: $option" >& 2
            exit 1
			;;
    esac
shift
done


if [[ "$team_size" == 4 ]] ; then
	team_size=q
elif [[ "$team_size" == 2 ]] ; then
	team_size=e
else
	echo "$0 : ERROR : Team size must be 2 or 4" >& 2
	exit 1
fi

################################################################################
# Get the php file containing the team numbers
################################################################################
INF1995_URL=http://www.groupes.polymtl.ca/inf1995/
site_section=equipes
file=index${team_size}${section}.php
file_URL=${INF1995_URL}/${site_section}/${file}
teams_file=teams.php
wget $file_URL --output-document=$teams_file > /dev/null 2>&1

################################################################################
# Extract team numbers from the file
################################################################################

#
# Regex for selecting lines from file using grep
# ==============================================
#
# <tr> <th>Juteau</th> <th>Godefroy</th> <th style="text-align: center;">7698</th> </tr> <!-- couriel est godefroy.juteau -->
# for reference in case the format changes.
team_line_regex='<tr> <th>.*</th>.*</th>.*-->'

#
# Parts for the sed substitution expression
# =========================================
#
# These lines break up into a part before the team number, matched by the regex
prefix=".*>"
# The team number
team_number_regex="[0-9]*"
# Then everything after the team number which is an optionnal extra part and
# then the rest
extra_part_regex=" ([0-9])" # Like the '(5)' in the following special line
postfix="\\(${extra_part_regex}\)*<\\/th>.*"  # everything after the team number
#
# Example special line with 'extra_part'
# <tr> <th>Binet</th> <th>Chelsy</th> <th style="text-align: center;">2455 (5)</th> </tr> <!-- couriel est chelsy.binet -->
# have a (5) in the place where the team number is.


#
# Running grep line selection and sed substitution
# ================================================
#
grep "${team_line_regex}" teams.php |
	sed "s/${prefix}\\(${team_number_regex}\\)${postfix}/\\1/" |
	sort | uniq | tr "\n" " "

rm $teams_file
