#!/bin/bash

################################################################################
# Script to retrieve values from a file of key=value pairs.
# options:
# get-value --key key-name [--file filename]
# -k | --key to specify the key for which we want to retrieve the value
# [-f | --file ] to specify the file where we want to look.  Defaults to
# settings.txt
################################################################################

################################################################################
# Option parsing with error checking
################################################################################
file=settings.txt
key=""
while [[ $# -gt 0 ]]
do
	option="$1"
	optarg="$2"
	case "$option" in
		-f|--file)
			file="$optarg"
			shift
			;;
		-k|--key)
			key="$optarg"
			shift
			;;
		*)
			echo "$0 : ERROR : Unknown option $option" >& 2
			exit 1
			;;
	esac
shift
done

if [[ "$key" == "" ]] ; then
	echo "$0 : ERROR :Key must be specified" >& 2
fi

################################################################################
# Search through file for matching line and extraction of value matching the
# key.  Output to stdout.
################################################################################
value=""
while read -r line; do
	if [[ $line == ${key}=* ]]; then
		value=${line#${key}=}
		echo "$value"
		exit 0
	fi
done < $file
echo "$0 : ERROR : key '$key' not found" >& 2
exit 1
